/*******************************************************************************************
*
*	raylib example 04a - Texture loading and drawing 
*
*	This example has been created using raylib 1.0 (www.raylib.com)
*	raylib is licensed under an unmodified zlib/libpng license (View raylib.h for details)
*
*	Copyright (c) 2013 Ramon Santamaria (Ray San - raysan@raysanweb.com)
*
********************************************************************************************/

#include "raylib.h"

int main()
{
	int screenWidth = 800;
	int screenHeight = 450;
	
	// Initialization
	//---------------------------------------------------------
	InitWindow(screenWidth, screenHeight, "raylib example 04a - texture loading and drawing");	// Window and context initialization
	
	// NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)
	Texture2D texture = LoadTexture("resources/raylib_logo.png");		// Texture loading
	//----------------------------------------------------------
	
    // Main game loop
    while (!WindowShouldClose())	// Detect window close button or ESC key
    {
		// Update
		//-----------------------------------------------------
		// TODO: Update your variables here
		//-----------------------------------------------------
		
		// Draw
		//-----------------------------------------------------
		BeginDrawing();
		
			ClearBackground(RAYWHITE);
			
			DrawTexture(texture, screenWidth/2 - texture.width/2, screenHeight/2 - texture.height/2, WHITE);
			
			DrawText("this IS a texture!", 360, 370, 10, 1, GRAY);
		
        EndDrawing();
		//-----------------------------------------------------
    }

	// De-Initialization
	//---------------------------------------------------------
	UnloadTexture(texture);		// Texture unloading
	
    CloseWindow();				// Close window and OpenGL context
	//----------------------------------------------------------
	
    return 0;
}